// ==========================================================================
// Flor Capeletto - Base de Datos de Servicios (Contenido de Marca Personal)
// Este archivo es la fuente de verdad. Al editar los textos aquí, se
// actualizarán en el planificador interno de servicios automáticamente.
// ==========================================================================

const SERVICIOS_DATA = {
    // 🧭 PESTAÑA 1: MENTORÍAS Y CONSULTORÍAS 1A1
    
    // A. Método NEXO (Programa Premium - Emprender / Marca Personal)
    nexoConcepto: "El Método NEXO es tu mentoría premium e individual diseñada para acompañar el salto al autoempleo, el emprendimiento de servicios y el desarrollo de tu marca personal. Fusiona la estrategia de posicionamiento en el mercado y comunicación con herramientas de gestión mental y emocional, y la regulación del estrés ante la incertidumbre.\n\nIdeal para:\n1. Profesionales en redefinición que desean independizarse, crear su propio negocio de servicios y monetizar su conocimiento.\n2. Emprendedores y Freelancers que necesitan estructurar su marca personal y posicionarse como referentes en su nicho.\n3. Emigrantes que deciden arrancar su propio camino laboral autónomo en un nuevo país (como Europa).\n\nPromesa de Valor: Diseñarás un negocio de servicios alineado con tu estilo de vida, estructurarás tus ofertas premium y comunicarás tu marca con total claridad, sosteniendo el proceso con un sistema nervioso regulado frente al miedo del cambio.",
    
    nexoEstructura: "El programa se compone de 4 sesiones individuales de alta intensidad y un soporte continuo, estructurados bajo el siguiente recorrido de transformación y blindados con salvaguardas de validación:\n\nSESIÓN 1: DIAGNÓSTICO PROFESIONAL Y PODER DEL SER (El Origen)\n* Qué vas a solucionar: Salir de la desorientación y la insatisfacción laboral. Identifico tus talentos latentes y tus bloqueos principales para establecer un punto de partida claro y realista.\n\nSESIÓN 2: DECONSTRUCCIÓN Y REDISEÑO DE IDENTIDAD (El Eje)\n* Qué vas a solucionar: Definir a quién vas a ayudar y qué problemas resuelves. Diseño contigo el perfil de tu cliente ideal y validás tu propuesta con entrevistas reales en tu nicho de mercado.\n\nSESIÓN 3: INGENIERÍA DE LA PROPUESTA Y VALOR DE MERCADO (El Hacer)\n* Qué vas a solucionar: Estructurar tus ofertas y fijar tus precios de forma estratégica. Diseño contigo tu Servicio Estrella Premium y preparás tu propuesta comercial.\n\nSESIÓN 4: COMUNICACIÓN, POSICIONAMIENTO Y ACCIÓN SOSTENIBLE (La Acción)\n* Qué vas a solucionar: Perder el miedo a vender y a cobrar lo que vales. Practico contigo simulaciones de venta y objeciones comunes, optimizo tu perfil de LinkedIn y definimos tu plan de acción a 90 días.",
    
    nexoIncluye: "- Cuestionario de Diagnóstico Previo (Pre-work) una semana antes de iniciar para alinear expectativas y auditar tus recursos.\n- Sesiones individuales 1 a 1 de forma online (Zoom/Meet), con tiempos flexibles adaptados a tu proceso.\n- Soporte continuo vía WhatsApp entre sesiones para co-pensar tus decisiones y revisar borradores.\n- Tu Notion Brand Tracker: base de datos personalizada para organizar tus ideas, contenidos y clientes.\n- Acceso prioritario y gratuito a todos mis infoproductos actuales y futuros.\n- Puente de soporte de 14 días vía WhatsApp post-programa exclusivo para auditar tu lanzamiento y tus primeros pasos reales.",
    
    nexoPrecio: "A consultar (Mentoría Premium)",
    
    nexoPasarelas: "Wise, PayPal, Transferencia bancaria (Italia / Argentina)",

    // B. Sesiones de Consultoría Enfocadas (Táctico - Búsqueda de Empleo / LinkedIn / Entrevistas)
    consultoriaConcepto: "Las Sesiones de Consultoría Enfocadas son sesiones 1 a 1 de resolución rápida y táctica para perfiles profesionales que buscan empleo de forma tradicional (local o internacional). Aquí aplico mi mirada de seleccionadora (mis 10+ años en RRHH corporativo) para optimizar tu postulación y entrenar tu discurso, eliminando la frustración de enviar CVs que nadie responde.",
    
    consultoriaEstructura: "Elegí la modalidad que se adapte a tu necesidad actual:\n\n1. SESIÓN LINKEDIN & CV BOOST (90 min)\nAuditoría en pantalla compartida y reescritura en vivo. Corrijo la estructura de tu CV para superar filtros automáticos ATS y optimizo tu perfil de LinkedIn (palabras clave, titular, sección Acerca de) para que aparezcas en las búsquedas de los reclutadores.\n*Incluye: Cuestionario previo, plantilla de CV adaptable a tu sector, listado de keywords personalizadas, la Guía Estratégica de LinkedIn 2026 y la Guía Práctica de CV de Impacto.*\n\n2. ENTRENAMIENTO Y SIMULACIÓN DE ENTREVISTAS (75 min)\nPráctica simulada e intensiva (en español o inglés) adaptada a una oferta real a la que quieras aplicar. Simulás una entrevista durante 45 min y te dedico 30 min a darte feedback al hueso sobre tu comunicación y estructuración de respuestas.\n*Incluye: Guía de estructuración de respuestas con método STAR, técnicas de respiración y mindfulness rápido para regular la ansiedad previa y la Guía Práctica de Entrevistas Laborales.*",
    
    consultoriaPrecio: "Sesión individual: €120 | Pack Inserción Completa (ambas sesiones): €200 (17% de descuento)\nMétodos de pago: PayPal, Wise, Transferencia bancaria (Italia / Argentina)",

    // 📚 PESTAÑA 2: INFOPRODUCTOS (Ebooks, Guías y Plantillas)
    infoTracker: "Notion Job Tracker PRO (El Toolkit de Búsqueda Activa):\nUna suite avanzada en Notion para estructurar tu búsqueda laboral en piloto automático y gestionar tus metas.\n\nQué incluye la versión PRO:\n1. Planner de Búsqueda Integrado: Planificador estratégico anual/mensual para organizar tus hábitos de postulación, estudio y red de contactos (iniciado por Flor, integrado al Core).\n2. CRM de Contactos y Reclutadores: Base de datos con alertas automáticas de seguimiento.\n3. Bóveda de Mensajes (Copy-Paste): Mensajes de outreach y seguimiento post-entrevista (Español/Inglés).\n4. Plantilla de Respuestas STAR: Para las 15 preguntas de entrevista más comunes.\n5. Diario de Regulación Emocional y Bienestar: Registro de self-care y mindfulness para mitigar el estrés.\n6. Biblioteca Loom: Tutoriales en video incrustados.\n\nPrecio sugerido: €19 (Lanzamiento: €14,90). *Se mantiene la versión básica gratuita como Lead Magnet.*",
    
    infoGuia: "Guía Estratégica de LinkedIn 2026 + Guía de CV de Impacto (Bono Plus):\neBook en PDF de 80 páginas con consejos prácticos de selección de personal y optimización de perfiles, ahora fusionado con el manual de CV como un extra de alto valor.\n\nEstrategia de Captación y Upsell:\n* Formato: Lead Magnet gratuito en la web.\n* Embudo de Ventas (Upsell): En el interior del PDF incorporamos enlaces estratégicos y cupones de descuento exclusivos (ej. 15% off) para derivar a los lectores hacia la compra del Notion Job Tracker PRO o la reserva de las Sesiones de Consultoría Enfocadas (CV Boost/Entrevistas).",
    
    infoNuevas: "Catálogo de Guías y Recursos Adicionales:\n\n1. GUÍA DE ENTREVISTAS LABORALES (Creada):\neBook práctico que recopila las preguntas difíciles de selección corporativa y pautas para estructurar tus respuestas profesionales sin titubeos.\n\n2. GUÍA DE BÚSQUEDA DE EMPLEO (Creada):\nManual de metodología técnica para estructurar postulaciones eficientes, analizar empresas y gestionar el tiempo de búsqueda diaria.\n\n3. GUÍA DE ENTREVISTAS PARA EMIGRANTES (A Desarrollar):\nGuía enfocada en el mercado Europeo/Italiano. Aborda el choque cultural en procesos de selección internacionales, la deconstrucción y traducción de tu trayectoria latinoamericana para encajar en el perfil europeo, y herramientas emocionales para transitar la desorientación y el duelo migratorio laboral.",

    // 🎥 PESTAÑA 3: TALLERES Y CURSOS PREGRABADOS
    talleresLista: "1. TALLER 1: DEL BLOQUEO A LA ACCIÓN (Gestión Emocional y Mindfulness para el Cambio)\n* Público Ideal: Profesionales en transición, emigrantes o futuros independientes que se sienten paralizados ante la incertidumbre, procrastinan su búsqueda o sufren de alta ansiedad antes de entrevistas o de exponerse digitalmente.\n* Qué soluciona: Te enseña cómo reaccionamos internamente ante el cambio (por qué nos congelamos) y te da herramientas de enfoque y respiración de 5 minutos para regular el estrés en tiempo real, pasando de la parálisis al foco y la acción constante.\n\n2. TALLER 2: LINKEDIN DE ALTO IMPACTO (Paso a Paso en Pantalla)\n* Público Ideal: Profesionales que buscan empleo o clientes y tienen su perfil desactualizado, incompleto o no saben cómo utilizar la red estratégicamente.\n* Qué soluciona: Taller 100% práctico en pantalla para configurar tu perfil como un imán de recruiters, optimizar tu titular, redactar tu extracto y entender cómo funciona el algoritmo de búsqueda.\n\n3. TALLER 3: EMIGRAR Y TRABAJAR EN EUROPA (Estrategia y Mentalidad)\n* Público Ideal: Profesionales latinoamericanos que han emigrado o están planificando emigrar a Italia o el resto de Europa y se sienten desorientados.\n* Qué soluciona: Claves para reencuadrar tu experiencia internacional, cómo contactar a recruiters europeos y herramientas de gestión del duelo migratorio laboral.",
    
    talleresHosting: "Hotmart (gestión de cobro automatizada e impuestos de la UE controlados) o Teachable.",
    
    talleresPrecio: "Por definir (Ej. €29 - €49 por taller)",
    
    talleresPromo: "20% de descuento en el lanzamiento para registrados en la lista de espera de la web."
};
